### ISSUE TITLE
Coordinator tool - Print message once decryption of the final result starts

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-governance-committee-voting#84] opened 2024-03-08 13:09 UTC
**Description**
After the command to finalize the result was used, it looks like the tool is hanging while it is combining decryptions.

**Steps to Reproduce**
` .\election-coordinator.exe final-result --contract "<8324,0>" --node "https://grpc.testnet.concordium.com:20000"`

**Expected Result**
After user has called the command, output message explaining what is going on. Maybe it would be nice to write output something  as "Finalizing results...", idk if loading bar is applicable here as well.

**Actual Result**
After calling the command, nothing is outputted until finalization is done, then the result is outputted.

*Versions**
- Software Version: 0.2.0
- OS: Windows

**Comment by soerenbf** [comment] 2024-03-13 07:31
This is more or less a duplicate of #55, but with a more elaborate description. Will close #55 in favour of this.

**Closed** 2024-03-14 09:03 UTC
Labels: [Prio] High, [Type] Change Request
